const STORAGE_KEY='offshore-fishing-region-system-v2';
const DEFAULT_SCENE={width:1600,height:900,url:'./assets/offshore-chart-fallback.svg'};
const DEFAULT_OPTIONS={Tags:['近海','外海','深海','礁石','沉船','灯塔','港口','危险','稀有','任务'],RegionCategory:['BaseSeaArea','PoiInfluenceArea','EventArea']};
const ENABLED_OPTIONS=['Enabled','Disabled'];
const CATEGORY_COLORS={BaseSeaArea:'#3b82f6',PoiInfluenceArea:'#22c55e',EventArea:'#ef4444'};
const DEFAULT_SCHEMA={sections:[{id:'basic',title:'基础属性',fields:[{key:'RegionId',label:'RegionId',type:'text'},{key:'Name',label:'Name',type:'text'},{key:'RegionCategory',label:'RegionCategory',type:'select',source:'RegionCategory'},{key:'Tags',label:'Tags',type:'multiselect',source:'Tags'},{key:'Priority',label:'Priority',type:'number'},{key:'ParentRegionId',label:'ParentRegionId',type:'text'},{key:'Enabled',label:'Enabled',type:'boolean'}]},{id:'spatial',title:'空间范围',fields:[{key:'GeometryIds',label:'GeometryIds',type:'list'}]},{id:'interaction',title:'交互规则',fields:[{key:'AccessRuleProfileId',label:'AccessRuleProfileId',type:'text'},{key:'TraversalProfileId',label:'TraversalProfileId',type:'text'},{key:'InteractionProfileId',label:'InteractionProfileId',type:'text'},{key:'EnvironmentProfileId',label:'EnvironmentProfileId',type:'text'}]},{id:'output',title:'产出内容',fields:[{key:'FishSpawnProfileId',label:'FishSpawnProfileId',type:'text'}]},{id:'support',title:'辅助',fields:[{key:'LinkedPoiIds',label:'LinkedPoiIds',type:'list'},{key:'SortOrder',label:'SortOrder',type:'number'},{key:'Description',label:'Description',type:'textarea'}]}]};
const SAMPLE_REGIONS=[{RegionId:'sea-region-001',Name:'北侧礁群缓冲区',RegionCategory:'PoiInfluenceArea',Tags:['近海','礁石','危险'],Priority:60,ParentRegionId:'sea-parent-001',Enabled:true,GeometryIds:['geom-sea-region-001-a'],AccessRuleProfileId:'access-reef-caution',TraversalProfileId:'traversal-rock-current',InteractionProfileId:'interaction-reef-fishing',EnvironmentProfileId:'env-cold-surge-01',FishSpawnProfileId:'fishspawn-reef-night-a',LinkedPoiIds:['poi-reef-01','poi-wreck-02'],SortOrder:10,Description:'礁石边缘浪涌明显，适合设计为高风险高回报的近海作业区。',Geometry:{Type:'Polygon',Points:[[280,260],[520,210],[610,360],[340,420]],Center:[],Radius:0}},{RegionId:'sea-region-002',Name:'外海灯塔事件圈',RegionCategory:'EventArea',Tags:['外海','灯塔','任务','稀有'],Priority:80,ParentRegionId:'sea-parent-002',Enabled:true,GeometryIds:['geom-sea-region-002-a'],AccessRuleProfileId:'access-event-window',TraversalProfileId:'traversal-open-sea',InteractionProfileId:'interaction-lighthouse-signal',EnvironmentProfileId:'env-storm-band-02',FishSpawnProfileId:'fishspawn-rare-pelagic',LinkedPoiIds:['poi-lighthouse-07'],SortOrder:20,Description:'事件区围绕灯塔影响生成，适合挂接限时事件、稀有鱼刷新和引导任务。',Geometry:{Type:'Circle',Points:[],Center:[980,340],Radius:130}}];
const $=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v)),uid=p=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;
const state={scene:{...DEFAULT_SCENE},options:clone(DEFAULT_OPTIONS),schema:clone(DEFAULT_SCHEMA),regions:[],sketchLayers:[],selectedId:null,selectedLayerKey:null,showUnmatched:true,layers:new Map(),filters:{tags:new Set(),fish:new Set(),categories:new Set(),enabled:new Set()},brush:{enabled:false,drawing:false,radius:28,points:[],preview:null},sketch:{enabled:false,drawing:false,width:3,points:[],preview:null}};
const els={mapUpload:$('#map-upload'),configUpload:$('#config-upload'),exportConfig:$('#export-config'),clearStorage:$('#clear-storage'),optionsTags:$('#options-tags'),optionsCategories:$('#options-categories'),schemaConfig:$('#schema-config'),applyOptions:$('#apply-options'),loadSample:$('#load-sample'),tagFilter:$('#tag-filter-select'),fishFilter:$('#fish-filter-select'),categoryFilter:$('#category-filter-select'),modeFilter:$('#mode-filter-select'),toggleBrush:$('#toggle-brush'),brushSize:$('#brush-size'),brushSizeValue:$('#brush-size-value'),toggleSketch:$('#toggle-sketch'),sketchWidth:$('#sketch-width'),sketchWidthValue:$('#sketch-width-value'),resetFilters:$('#reset-filters'),toggleUnmatched:$('#toggle-unmatched'),regionList:$('#region-list'),layerList:$('#layer-list'),deleteLayer:$('#delete-layer'),activeRegionName:$('#active-region-name'),visibleRegionCount:$('#visible-region-count'),cursorCoords:$('#cursor-coords'),detailCategory:$('#detail-category'),detailName:$('#detail-name'),detailDescription:$('#detail-description'),detailTags:$('#detail-tags'),detailSections:$('#detail-sections'),editorSections:$('#region-editor-sections'),saveRegion:$('#save-region'),resetEditor:$('#reset-editor'),deleteRegion:$('#delete-region')};
const map=L.map('map',{crs:L.CRS.Simple,minZoom:-2,maxZoom:3,zoomSnap:.25,attributionControl:false});let bounds=[[0,0],[state.scene.height,state.scene.width]],overlay=L.imageOverlay(state.scene.url,bounds,{interactive:false}).addTo(map);const drawnItems=new L.FeatureGroup().addTo(map);map.fitBounds(bounds);L.control.zoom({position:'bottomright'}).addTo(map);map.addControl(new L.Control.Draw({position:'topleft',draw:{polyline:false,marker:false,circlemarker:false,polygon:{allowIntersection:false,shapeOptions:{color:CATEGORY_COLORS.BaseSeaArea,weight:2,fillOpacity:.28}},rectangle:{shapeOptions:{color:CATEGORY_COLORS.PoiInfluenceArea,weight:2,fillOpacity:.28}},circle:{shapeOptions:{color:CATEGORY_COLORS.EventArea,weight:2,fillOpacity:.28}}},edit:{featureGroup:drawnItems}}));
const selRegion=()=>state.regions.find(r=>r.RegionId===state.selectedId)||null,fields=()=>state.schema.sections.flatMap(s=>s.fields||[]),listText=t=>t.split('\n').map(v=>v.trim()).filter(Boolean),fishProfiles=()=>[...new Set(state.regions.map(r=>r.FishSpawnProfileId).filter(Boolean))].sort(),selVals=s=>new Set([...s.selectedOptions].map(o=>o.value));
function normalizeScene(s){return{url:s?.url||DEFAULT_SCENE.url,width:Number(s?.width)||DEFAULT_SCENE.width,height:Number(s?.height)||DEFAULT_SCENE.height}}
function normalizeOptions(o){return{Tags:Array.isArray(o?.Tags)?o.Tags.map(String).filter(Boolean):clone(DEFAULT_OPTIONS.Tags),RegionCategory:Array.isArray(o?.RegionCategory)?o.RegionCategory.map(String).filter(Boolean):clone(DEFAULT_OPTIONS.RegionCategory)}}
function normalizeSchema(s){if(!s||!Array.isArray(s.sections)||!s.sections.length)return clone(DEFAULT_SCHEMA);return{sections:s.sections.map((x,i)=>({id:x.id||`section-${i+1}`,title:x.title||x.id||`Section ${i+1}`,fields:Array.isArray(x.fields)?x.fields.map((f,j)=>({key:f.key||`Field${i+1}_${j+1}`,label:f.label||f.key||`Field ${j+1}`,type:f.type||'text',source:f.source||null,options:Array.isArray(f.options)?f.options.map(String):null})):[]}))}}
function normalizeGeometry(g){if(g?.Type==='Circle')return{Type:'Circle',Points:[],Center:[Number(g.Center?.[0])||0,Number(g.Center?.[1])||0],Radius:Number(g.Radius||0)};const p=Array.isArray(g?.Points)?g.Points.map(v=>[Number(v[0])||0,Number(v[1])||0]):[];return{Type:g?.Type==='Rectangle'?'Rectangle':'Polygon',Points:p,Center:[],Radius:0}}
function normalizeRegion(r){const x={RegionId:String(r?.RegionId||uid('region')),Name:String(r?.Name||''),RegionCategory:String(r?.RegionCategory||state.options.RegionCategory[0]||DEFAULT_OPTIONS.RegionCategory[0]),Tags:Array.isArray(r?.Tags)?r.Tags.map(String).filter(Boolean):[],Priority:Number(r?.Priority||0),ParentRegionId:String(r?.ParentRegionId||''),Enabled:r?.Enabled!==undefined?Boolean(r.Enabled):true,GeometryIds:Array.isArray(r?.GeometryIds)?r.GeometryIds.map(String).filter(Boolean):[],AccessRuleProfileId:String(r?.AccessRuleProfileId||''),TraversalProfileId:String(r?.TraversalProfileId||''),InteractionProfileId:String(r?.InteractionProfileId||''),EnvironmentProfileId:String(r?.EnvironmentProfileId||''),FishSpawnProfileId:String(r?.FishSpawnProfileId||''),LinkedPoiIds:Array.isArray(r?.LinkedPoiIds)?r.LinkedPoiIds.map(String).filter(Boolean):[],SortOrder:Number(r?.SortOrder||0),Description:String(r?.Description||''),Geometry:normalizeGeometry(r?.Geometry)};if(!x.GeometryIds.length)x.GeometryIds=[`geom-${x.RegionId}`];return x}
function normalizeSketchLayer(l,i){return{LayerId:String(l?.LayerId||uid('sketch')),LayerType:'Sketch',Name:String(l?.Name||`线稿图层 ${i+1}`),Geometry:{Type:'OpenPath',Points:Array.isArray(l?.Geometry?.Points)?l.Geometry.Points.map(p=>[Number(p[0])||0,Number(p[1])||0]):[]},Style:{Color:l?.Style?.Color||'#ffffff',Weight:Number(l?.Style?.Weight||3),DashArray:l?.Style?.DashArray||'8 6'}}}
function saveStorage(){localStorage.setItem(STORAGE_KEY,JSON.stringify({scene:state.scene,options:state.options,schema:state.schema,regions:state.regions,sketchLayers:state.sketchLayers,showUnmatched:state.showUnmatched}))}
function loadStorage(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return false;try{const p=JSON.parse(raw);state.options=normalizeOptions(p.options);state.schema=normalizeSchema(p.schema);const s=normalizeScene(p.scene);setScene(s.url,s.width,s.height,false);state.regions=Array.isArray(p.regions)?p.regions.map(normalizeRegion):[];state.sketchLayers=Array.isArray(p.sketchLayers)?p.sketchLayers.map(normalizeSketchLayer):[];state.showUnmatched=p.showUnmatched!==undefined?!!p.showUnmatched:true;return true}catch(e){console.error(e);return false}}
function setScene(url,width,height,persist=true){state.scene={url,width,height};bounds=[[0,0],[height,width]];if(overlay)map.removeLayer(overlay);overlay=L.imageOverlay(url,bounds,{interactive:false}).addTo(map);map.fitBounds(bounds);if(persist)saveStorage()}
function geometryFromLayer(layer){if(layer instanceof L.Circle){const c=layer.getLatLng();return{Type:'Circle',Points:[],Center:[c.lng,c.lat],Radius:layer.getRadius()}}return{Type:layer instanceof L.Rectangle?'Rectangle':'Polygon',Points:(layer.getLatLngs()[0]||[]).map(p=>[p.lng,p.lat]),Center:[],Radius:0}}
function layerFromRegion(r){if(r.Geometry.Type==='Circle')return L.circle([r.Geometry.Center[1],r.Geometry.Center[0]],{radius:r.Geometry.Radius});const p=r.Geometry.Points.map(v=>[v[1],v[0]]);return r.Geometry.Type==='Rectangle'?L.rectangle(p):L.polygon(p)}
function nPoint(p){const len=Math.hypot(p.x,p.y)||1;return{x:p.x/len,y:p.y/len}}
function strokeToPolygon(points,r){if(points.length<2){const p=points[0];return[[p.lng-r,p.lat-r],[p.lng+r,p.lat-r],[p.lng+r,p.lat+r],[p.lng-r,p.lat+r]]}const left=[],right=[];for(let i=0;i<points.length;i+=1){const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],t=nPoint({x:next.lng-prev.lng,y:next.lat-prev.lat}),n={x:-t.y,y:t.x};left.push([points[i].lng+n.x*r,points[i].lat+n.y*r]);right.unshift([points[i].lng-n.x*r,points[i].lat-n.y*r])}return[...left,...right]}
function fieldOptions(f){if(f.source==='Tags')return state.options.Tags;if(f.source==='RegionCategory')return state.options.RegionCategory;return Array.isArray(f.options)?f.options:[]}
function formatValue(f,v){if(Array.isArray(v))return v.length?v.join(', '):'-';if(f.type==='boolean')return v?'true':'false';return v===''||v===undefined||v===null?'-':String(v)}
function controlFor(f,v){let c,ops=fieldOptions(f);if(f.type==='textarea'){c=document.createElement('textarea');c.rows=4;c.value=v||''}else if(f.type==='number'){c=document.createElement('input');c.type='number';c.value=Number(v||0)}else if(f.type==='boolean'){c=document.createElement('select');c.innerHTML='<option value="true">true</option><option value="false">false</option>';c.value=v?'true':'false'}else if(f.type==='select'){c=document.createElement('select');c.innerHTML=ops.map(o=>`<option value="${o}">${o}</option>`).join('');c.value=v||ops[0]||''}else if(f.type==='multiselect'){c=document.createElement('select');c.multiple=true;c.size=Math.max(4,Math.min(8,ops.length||4));c.innerHTML=ops.map(o=>`<option value="${o}">${o}</option>`).join('');[...c.options].forEach(o=>o.selected=Array.isArray(v)&&v.includes(o.value))}else if(f.type==='list'){c=document.createElement('textarea');c.rows=4;c.value=Array.isArray(v)?v.join('\n'):''}else{c=document.createElement('input');c.type='text';c.value=v||''}c.dataset.fieldKey=f.key;c.dataset.fieldType=f.type;return c}
function renderDetailSections(r){els.detailSections.innerHTML='';state.schema.sections.forEach(s=>{const card=document.createElement('section');card.className='schema-section';card.innerHTML=`<div class="panel__header"><span>${s.title}</span><span class="panel__meta">${s.id}</span></div>`;const grid=document.createElement('div');grid.className='detail-grid';s.fields.forEach(f=>{const item=document.createElement('div');item.className='info-item';item.innerHTML=`<span class="info-item__label">${f.label}</span><strong>${formatValue(f,r[f.key])}</strong>`;grid.appendChild(item)});if(s.id==='spatial'){const item=document.createElement('div');item.className='info-item';item.innerHTML=`<span class="info-item__label">GeometryType</span><strong>${r.Geometry.Type}</strong>`;grid.appendChild(item)}card.appendChild(grid);els.detailSections.appendChild(card)})}
function renderEditorSections(region){const r=region||normalizeRegion({Geometry:{Type:'Polygon',Points:[],Center:[],Radius:0}});els.editorSections.innerHTML='';state.schema.sections.forEach(s=>{const card=document.createElement('section');card.className='schema-section';card.innerHTML=`<div class="panel__header"><span>${s.title}</span><span class="panel__meta">${s.id}</span></div>`;const grid=document.createElement('div');grid.className='form-grid';s.fields.forEach(f=>{const label=document.createElement('label');label.className=`form-field${f.type==='textarea'||f.type==='multiselect'||f.type==='list'?' form-field--full':''}`;label.innerHTML=`<span>${f.label}</span>`;label.appendChild(controlFor(f,r[f.key]));grid.appendChild(label)});if(s.id==='spatial'){const label=document.createElement('label');label.className='form-field form-field--full';label.innerHTML=`<span>GeometryType</span><input type="text" value="${r.Geometry.Type}" readonly>`;grid.appendChild(label)}card.appendChild(grid);els.editorSections.appendChild(card)})}
function updateDetail(r){if(!r){els.activeRegionName.textContent='未选择';els.detailCategory.textContent='None';els.detailName.textContent='未选择区域';els.detailDescription.textContent='点击一个区域后，这里会按 5 个属性分区显示字段信息。';els.detailTags.innerHTML='';els.detailSections.innerHTML='';return}els.activeRegionName.textContent=r.Name||r.RegionId;els.detailCategory.textContent=r.RegionCategory;els.detailName.textContent=r.Name||r.RegionId;els.detailDescription.textContent=r.Description||'暂无备注。';els.detailTags.innerHTML=r.Tags.map(t=>`<span class="detail-tag">${t}</span>`).join('');renderDetailSections(r)}
function fillEditor(r){state.selectedId=r?r.RegionId:null;renderEditorSections(r);els.deleteRegion.disabled=!r;updateDetail(r)}
function readEditorValues(){const out={};fields().forEach(f=>{const i=els.editorSections.querySelector(`[data-field-key="${f.key}"]`);if(!i)return;if(f.type==='number')out[f.key]=Number(i.value||0);else if(f.type==='boolean')out[f.key]=i.value==='true';else if(f.type==='multiselect')out[f.key]=[...i.selectedOptions].map(o=>o.value);else if(f.type==='list')out[f.key]=listText(i.value);else out[f.key]=i.value.trim()});return out}
function renderRegionList(visible){els.regionList.innerHTML='';if(!state.regions.length){els.regionList.innerHTML='<div class="empty-state">还没有区域。请先绘制一个区域。</div>';return}visible.forEach(r=>{const b=document.createElement('button');b.type='button';b.className=`region-card${r.RegionId===state.selectedId?' is-active':''}`;b.innerHTML=`<span><strong>${r.Name||r.RegionId}</strong><span class="region-card__meta">${r.RegionCategory} | ${r.Enabled?'Enabled':'Disabled'}</span></span><span class="panel__meta">${r.Tags.join('/')||'-'}</span>`;b.addEventListener('click',()=>selectRegion(r.RegionId,true));els.regionList.appendChild(b)})}
function renderLayerList(){els.layerList.innerHTML='';const items=[...state.regions.map(r=>({key:`region:${r.RegionId}`,title:r.Name||r.RegionId,meta:`${r.Geometry.Type} | ${r.RegionCategory}`,click:()=>selectRegion(r.RegionId,true)})),...state.sketchLayers.map(s=>({key:`sketch:${s.LayerId}`,title:s.Name,meta:`${s.Geometry.Type} | width ${s.Style.Weight}`,click:()=>{state.selectedLayerKey=`sketch:${s.LayerId}`;renderLayerList()}}))];if(!items.length){els.layerList.innerHTML='<div class="empty-state">还没有图层。</div>';return}items.forEach(it=>{const b=document.createElement('button');b.type='button';b.className=`region-card${it.key===state.selectedLayerKey?' is-active':''}`;b.innerHTML=`<span><strong>${it.title}</strong><span class="layer-card__type">${it.meta}</span></span>`;b.addEventListener('click',it.click);els.layerList.appendChild(b)})}
function selectRegion(id,fit=false){state.selectedId=id;state.selectedLayerKey=`region:${id}`;const r=selRegion();fillEditor(r);renderRegions();const layer=state.layers.get(`region:${id}`);if(fit&&layer?.getBounds)map.fitBounds(layer.getBounds(),{padding:[40,40]})}
function allow(selected,available,predicate){if(!available.length)return true;if(!selected.size)return false;return predicate()}
function matches(r){return allow(state.filters.tags,state.options.Tags,()=>r.Tags.some(t=>state.filters.tags.has(t)))&&allow(state.filters.fish,fishProfiles(),()=>state.filters.fish.has(r.FishSpawnProfileId))&&allow(state.filters.categories,state.options.RegionCategory,()=>state.filters.categories.has(r.RegionCategory))&&allow(state.filters.enabled,ENABLED_OPTIONS,()=>state.filters.enabled.has(r.Enabled?'Enabled':'Disabled'))}
function styleLayer(layer,r,matched,selected){const c=CATEGORY_COLORS[r.RegionCategory]||CATEGORY_COLORS.BaseSeaArea;layer.setStyle({color:c,weight:selected?4:2,fillColor:c,fillOpacity:matched?0.28:0.08,opacity:matched?0.96:0.18})}
function renderSketchLayers(){state.sketchLayers.forEach(s=>{const layer=L.polyline(s.Geometry.Points.map(p=>[p[1],p[0]]),{color:s.Style.Color,weight:s.Style.Weight,dashArray:s.Style.DashArray,opacity:.95});layer.__layerKey=`sketch:${s.LayerId}`;layer.bindTooltip(s.Name,{sticky:true});layer.on('click',()=>{state.selectedLayerKey=layer.__layerKey;renderLayerList()});drawnItems.addLayer(layer);state.layers.set(layer.__layerKey,layer)})}
function renderFilters(){setSelect(els.tagFilter,state.options.Tags,state.filters.tags);setSelect(els.fishFilter,fishProfiles(),state.filters.fish);setSelect(els.categoryFilter,state.options.RegionCategory,state.filters.categories);setSelect(els.modeFilter,ENABLED_OPTIONS,state.filters.enabled)}
function setSelect(sel,vals,set){sel.innerHTML=vals.map(v=>`<option value="${v}">${v}</option>`).join('');[...sel.options].forEach(o=>o.selected=set.has(o.value))}
function renderRegions(){drawnItems.clearLayers();state.layers.clear();const visible=[];state.regions.forEach(r=>{const matched=matches(r),selected=r.RegionId===state.selectedId;if(matched)visible.push(r);if(matched||state.showUnmatched){const layer=layerFromRegion(r);layer.__regionId=r.RegionId;layer.__layerKey=`region:${r.RegionId}`;styleLayer(layer,r,matched,selected);layer.bindTooltip(`${r.Name||r.RegionId} | ${r.Tags.join(', ')||'No Tags'}`,{sticky:true});layer.on('click',()=>selectRegion(r.RegionId,false));drawnItems.addLayer(layer);state.layers.set(layer.__layerKey,layer)}});renderSketchLayers();els.visibleRegionCount.textContent=String(visible.length);renderRegionList(visible);renderLayerList();updateDetail(selRegion())}
function renderAll(){renderFilters();renderRegions()}
function fitToRenderedLayers(){const ls=[...state.layers.values()].filter(l=>typeof l.getBounds==='function');if(!ls.length){map.fitBounds(bounds);return}map.fitBounds(L.featureGroup(ls).getBounds(),{padding:[40,40]})}
function syncTextareas(){els.optionsTags.value=state.options.Tags.join('\n');els.optionsCategories.value=state.options.RegionCategory.join('\n');els.schemaConfig.value=JSON.stringify(state.schema,null,2);els.toggleUnmatched.textContent=state.showUnmatched?'显示全部':'仅显示命中'}
function ensureFilterDefaults(force=false){if(!force)return;state.filters.tags=new Set(state.options.Tags);state.filters.fish=new Set(fishProfiles());state.filters.categories=new Set(state.options.RegionCategory);state.filters.enabled=new Set(ENABLED_OPTIONS)}
function syncFiltersAndRender(){state.filters.tags=selVals(els.tagFilter);state.filters.fish=selVals(els.fishFilter);state.filters.categories=selVals(els.categoryFilter);state.filters.enabled=selVals(els.modeFilter);renderAll()}
function createRegion(geometry){const r=normalizeRegion({Geometry:geometry,RegionId:uid('region'),GeometryIds:[uid('geom')]});state.regions.push(r);state.selectedId=r.RegionId;state.selectedLayerKey=`region:${r.RegionId}`;saveStorage();renderAll();fillEditor(r)}
function importConfig(text){const p=JSON.parse(text);state.options=normalizeOptions(p.options);state.schema=normalizeSchema(p.schema);const s=normalizeScene(p.scene);setScene(s.url,s.width,s.height,false);state.regions=(Array.isArray(p.regions)?p.regions:[]).map(normalizeRegion);state.sketchLayers=(Array.isArray(p.sketchLayers)?p.sketchLayers:[]).map(normalizeSketchLayer);state.selectedId=null;state.selectedLayerKey=null;ensureFilterDefaults(true);syncTextareas();saveStorage();fillEditor(null);renderAll();fitToRenderedLayers()}
function loadSample(includeRegions=true){state.options=clone(DEFAULT_OPTIONS);state.schema=clone(DEFAULT_SCHEMA);state.regions=includeRegions?SAMPLE_REGIONS.map(normalizeRegion):[];state.sketchLayers=[];state.selectedId=null;state.selectedLayerKey=null;state.showUnmatched=true;ensureFilterDefaults(true);syncTextareas();saveStorage();fillEditor(null);renderAll();if(includeRegions)fitToRenderedLayers()}
function loadLocalImage(file,cb){const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
function loadTextFile(file,cb){const r=new FileReader();r.onload=()=>cb(r.result);r.readAsText(file,'utf-8')}
map.on(L.Draw.Event.CREATED,e=>createRegion(geometryFromLayer(e.layer)));
map.on(L.Draw.Event.EDITED,e=>{e.layers.eachLayer(layer=>{const r=state.regions.find(v=>v.RegionId===layer.__regionId);if(r)r.Geometry=geometryFromLayer(layer)});saveStorage();renderAll()});
map.on(L.Draw.Event.DELETED,e=>{const ids=[];e.layers.eachLayer(layer=>{if(layer.__regionId)ids.push(layer.__regionId)});state.regions=state.regions.filter(r=>!ids.includes(r.RegionId));if(ids.includes(state.selectedId))fillEditor(null);saveStorage();renderAll()});
map.on('mousedown',e=>{if(state.sketch.enabled){state.sketch.drawing=true;state.sketch.points=[e.latlng];map.dragging.disable();if(state.sketch.preview)map.removeLayer(state.sketch.preview);state.sketch.preview=null;return}if(!state.brush.enabled)return;state.brush.drawing=true;state.brush.points=[e.latlng];map.dragging.disable();if(state.brush.preview)map.removeLayer(state.brush.preview);state.brush.preview=null});
map.on('mousemove',e=>{els.cursorCoords.textContent=`${Math.round(e.latlng.lng)}, ${Math.round(e.latlng.lat)}`;if(state.sketch.enabled&&state.sketch.drawing){state.sketch.points.push(e.latlng);if(state.sketch.preview)map.removeLayer(state.sketch.preview);state.sketch.preview=L.polyline(state.sketch.points,{color:'#ffffff',weight:state.sketch.width,dashArray:'8 6',opacity:.95,interactive:false}).addTo(map);return}if(!state.brush.enabled||!state.brush.drawing)return;state.brush.points.push(e.latlng);const outline=strokeToPolygon(state.brush.points,state.brush.radius);if(state.brush.preview)map.removeLayer(state.brush.preview);state.brush.preview=L.polygon(outline.map(p=>[p[1],p[0]]),{color:'#38bdf8',weight:2,fillColor:'#38bdf8',fillOpacity:.18,interactive:false}).addTo(map)});
function endBrush(){if(!state.brush.enabled||!state.brush.drawing)return;state.brush.drawing=false;map.dragging.enable();if(state.brush.points.length>=2)createRegion({Type:'Polygon',Points:strokeToPolygon(state.brush.points,state.brush.radius),Center:[],Radius:0});if(state.brush.preview)map.removeLayer(state.brush.preview);state.brush.preview=null;state.brush.points=[]}
function endSketch(){if(!state.sketch.enabled||!state.sketch.drawing)return;state.sketch.drawing=false;map.dragging.enable();if(state.sketch.points.length>=2){state.sketchLayers.push({LayerId:uid('sketch'),LayerType:'Sketch',Name:`线稿图层 ${state.sketchLayers.length+1}`,Geometry:{Type:'OpenPath',Points:state.sketch.points.map(p=>[p.lng,p.lat])},Style:{Color:'#ffffff',Weight:state.sketch.width,DashArray:'8 6'}});saveStorage();renderAll()}if(state.sketch.preview)map.removeLayer(state.sketch.preview);state.sketch.preview=null;state.sketch.points=[]}
map.on('mouseup',()=>{if(state.sketch.drawing)endSketch();else endBrush()});map.on('mouseout',()=>{if(state.sketch.drawing)endSketch();if(state.brush.drawing)endBrush()});
els.mapUpload.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;loadLocalImage(f,res=>{const img=new Image();img.onload=()=>setScene(res,img.width,img.height);img.src=res})});
els.applyOptions.addEventListener('click',()=>{state.options={Tags:listText(els.optionsTags.value),RegionCategory:listText(els.optionsCategories.value)};try{state.schema=normalizeSchema(JSON.parse(els.schemaConfig.value))}catch(e){els.detailCategory.textContent='Error';els.detailName.textContent='Schema 解析失败';els.detailDescription.textContent='请检查 Region Schema JSON。';return}state.regions=state.regions.map(normalizeRegion);ensureFilterDefaults(true);syncTextareas();saveStorage();fillEditor(selRegion());renderAll()});
els.loadSample.addEventListener('click',()=>loadSample(true));
els.configUpload.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;loadTextFile(f,t=>{try{importConfig(t);els.configUpload.value=''}catch(err){console.error(err);els.detailCategory.textContent='Error';els.detailName.textContent='导入失败';els.detailDescription.textContent='JSON 解析失败，请检查文件格式。'}})});
els.exportConfig.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:2,scene:state.scene,options:state.options,schema:state.schema,regions:state.regions,sketchLayers:state.sketchLayers},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='offshore-fishing-regions.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)});
els.clearStorage.addEventListener('click',()=>{localStorage.removeItem(STORAGE_KEY);state.scene={...DEFAULT_SCENE};state.options=clone(DEFAULT_OPTIONS);state.schema=clone(DEFAULT_SCHEMA);state.regions=[];state.sketchLayers=[];state.selectedId=null;state.selectedLayerKey=null;state.showUnmatched=true;ensureFilterDefaults(true);setScene(state.scene.url,state.scene.width,state.scene.height,false);syncTextareas();fillEditor(null);renderAll()});
els.toggleBrush.addEventListener('click',()=>{state.brush.enabled=!state.brush.enabled;if(state.brush.enabled){state.sketch.enabled=false;els.toggleSketch.textContent='开启线稿';els.toggleSketch.classList.remove('brush-mode-on')}els.toggleBrush.textContent=state.brush.enabled?'关闭涂抹':'开启涂抹';els.toggleBrush.classList.toggle('brush-mode-on',state.brush.enabled)});
els.brushSize.addEventListener('input',e=>{state.brush.radius=Number(e.target.value);els.brushSizeValue.textContent=String(state.brush.radius)});
els.toggleSketch.addEventListener('click',()=>{state.sketch.enabled=!state.sketch.enabled;if(state.sketch.enabled){state.brush.enabled=false;els.toggleBrush.textContent='开启涂抹';els.toggleBrush.classList.remove('brush-mode-on')}els.toggleSketch.textContent=state.sketch.enabled?'关闭线稿':'开启线稿';els.toggleSketch.classList.toggle('brush-mode-on',state.sketch.enabled)});
els.sketchWidth.addEventListener('input',e=>{state.sketch.width=Number(e.target.value);els.sketchWidthValue.textContent=String(state.sketch.width)});
[els.tagFilter,els.fishFilter,els.categoryFilter,els.modeFilter].forEach(s=>s.addEventListener('change',syncFiltersAndRender));
els.resetFilters.addEventListener('click',()=>{ensureFilterDefaults(true);renderAll()});
els.toggleUnmatched.addEventListener('click',()=>{state.showUnmatched=!state.showUnmatched;syncTextareas();renderAll()});
els.saveRegion.addEventListener('click',()=>{const r=selRegion();if(!r){els.detailDescription.textContent='请先绘制一个区域，再填写右侧表单。';return}const prev=r.RegionId;Object.assign(r,readEditorValues());r.RegionId=r.RegionId||prev||uid('region');if(!r.GeometryIds.length)r.GeometryIds=[`geom-${r.RegionId}`];state.selectedId=r.RegionId;state.selectedLayerKey=`region:${r.RegionId}`;saveStorage();renderAll();fillEditor(r)});
els.resetEditor.addEventListener('click',()=>fillEditor(selRegion()));
els.deleteRegion.addEventListener('click',()=>{if(!state.selectedId)return;state.regions=state.regions.filter(r=>r.RegionId!==state.selectedId);state.selectedId=null;state.selectedLayerKey=null;saveStorage();fillEditor(null);renderAll()});
els.deleteLayer.addEventListener('click',()=>{if(!state.selectedLayerKey)return;const [kind,idPart]=state.selectedLayerKey.split(':');if(kind==='region')state.regions=state.regions.filter(r=>r.RegionId!==idPart);if(kind==='sketch')state.sketchLayers=state.sketchLayers.filter(s=>s.LayerId!==idPart);if(state.selectedId===idPart)state.selectedId=null;state.selectedLayerKey=null;saveStorage();fillEditor(null);renderAll()});
const hasStorage=loadStorage();if(!hasStorage)loadSample(true);ensureFilterDefaults(true);syncTextareas();fillEditor(null);renderAll();els.brushSizeValue.textContent=String(state.brush.radius);els.sketchWidthValue.textContent=String(state.sketch.width);
